<template>
  <el-dialog :model-value="visible" :title="$t('config.audio_resources.title')" width="860px" append-to-body destroy-on-close modal-class="bs-shade" @open="loadResources" @closed="stopPreview" @update:model-value="$emit('update:visible',$event)">
    <el-alert type="info" :closable="false" show-icon :title="$t('config.audio_resources.description')" />
    <section class="upload-panel">
      <el-input v-model="displayName" :placeholder="$t('config.audio_resources.name_placeholder')" maxlength="80" show-word-limit />
      <el-upload ref="uploadRef" drag :auto-upload="false" :limit="1" accept=".mp3,.wav,audio/mpeg,audio/wav" :on-change="handleFileChange" :on-remove="handleFileRemove">
        <el-icon class="upload-icon"><UploadFilled /></el-icon><div>{{ $t('config.audio_resources.upload_hint') }}</div><template #tip><small>{{ $t('config.audio_resources.upload_tip') }}</small></template>
      </el-upload>
      <el-button type="primary" :loading="uploading" :disabled="!selectedFile" @click="uploadAudio"><el-icon><Upload /></el-icon>{{ $t('config.audio_resources.upload') }}</el-button>
    </section>
    <div class="resource-toolbar"><b>{{ $t('config.audio_resources.library') }}</b><el-tag type="info" effect="plain">{{ $t('config.audio_resources.count',{count:resources.length}) }}</el-tag></div>
    <el-table v-loading="loading" :data="resources" max-height="390" empty-text="">
      <el-table-column :label="$t('config.audio_resources.name')" min-width="170"><template #default="{row}"><b>{{ row.name }}</b><small class="original-name">{{ row.originalName }}</small></template></el-table-column>
      <el-table-column :label="$t('config.audio_resources.format')" width="90"><template #default="{row}"><el-tag size="small">{{ String(row.extension || '').toUpperCase() }}</el-tag></template></el-table-column>
      <el-table-column :label="$t('config.audio_resources.size')" width="110"><template #default="{row}">{{ formatSize(row.size) }}</template></el-table-column>
      <el-table-column :label="$t('config.audio_resources.reference_status')" min-width="150"><template #default="{row}"><el-tooltip v-if="row.references?.length" :content="referenceText(row.references)" placement="top"><el-tag type="warning" effect="plain">{{ $t('config.audio_resources.referenced_count',{count:row.references.length}) }}</el-tag></el-tooltip><el-tag v-else type="success" effect="plain">{{ $t('config.audio_resources.not_referenced') }}</el-tag></template></el-table-column>
      <el-table-column :label="$t('button.operate')" width="190" fixed="right"><template #default="{row}"><el-button link type="primary" @click="togglePreview(row)"><el-icon><VideoPause v-if="playingId === row.id"/><VideoPlay v-else/></el-icon>{{ playingId === row.id ? $t('config.audio_resources.stop') : $t('config.audio_resources.preview') }}</el-button><el-button link type="primary" @click="renameResource(row)">{{ $t('button.modify') }}</el-button><el-button link type="danger" :disabled="Boolean(row.references?.length)" @click="removeResource(row)">{{ $t('button.delete') }}</el-button></template></el-table-column>
    </el-table>
    <template #footer><el-button type="primary" @click="$emit('update:visible',false)">{{ $t('button.close') }}</el-button></template>
  </el-dialog>
</template>

<script setup lang="ts">
import { onBeforeUnmount,ref } from 'vue';import { ElMessage,ElMessageBox } from 'element-plus';import { Upload,UploadFilled,VideoPause,VideoPlay } from '@element-plus/icons-vue';import { useI18n } from 'vue-i18n';import api from '@/api/index';
const props = defineProps<{visible:boolean}>();const emit = defineEmits<{(event:'update:visible',value:boolean):void;(event:'changed',resources:any[]):void}>();const { t } = useI18n();const loading = ref(false);const uploading = ref(false);const resources = ref<any[]>([]);const selectedFile = ref<any>(null);const displayName = ref('');const uploadRef = ref<any>();const playingId = ref('');let previewAudio:HTMLAudioElement|null = null;let previewUrl = '';
const responseMessage = (error:any) => error?.response?.data?.detail || error?.response?.data?.msg || error?.message || t('message.messagetext.error_service');
const loadResources = async () => {loading.value = true;try {const {data} = await api.getAudioResources();if (!data?.status) throw new Error(data?.msg || t('config.audio_resources.load_failed'));resources.value = Array.isArray(data.datas) ? data.datas : [];emit('changed',resources.value)} catch (error:any) {ElMessage.error(responseMessage(error))} finally {loading.value = false}};
const handleFileChange = (file:any) => {const extension = String(file?.name || '').toLowerCase().split('.').pop();if (!['mp3','wav'].includes(extension)) {selectedFile.value = null;uploadRef.value?.clearFiles();return ElMessage.error(t('config.audio_resources.invalid_file'))}selectedFile.value = file.raw;if (!displayName.value.trim()) displayName.value = String(file.name || '').replace(/\.[^.]+$/,'')};const handleFileRemove = () => {selectedFile.value = null};
const uploadAudio = async () => {if (!selectedFile.value) return;uploading.value = true;try {const formData = new FormData();formData.append('file',selectedFile.value);formData.append('name',displayName.value.trim());const {data} = await api.uploadAudioResource(formData);if (!data?.status) throw new Error(data?.msg || t('config.audio_resources.upload_failed'));ElMessage.success(t('config.audio_resources.upload_success'));selectedFile.value = null;displayName.value = '';uploadRef.value?.clearFiles();await loadResources()} catch (error:any) {ElMessage.error(responseMessage(error))} finally {uploading.value = false}};
const stopPreview = () => {if (previewAudio) {previewAudio.pause();previewAudio.src = ''}previewAudio = null;playingId.value = '';if (previewUrl) URL.revokeObjectURL(previewUrl);previewUrl = ''};
const togglePreview = async (row:any) => {if (playingId.value === row.id) return stopPreview();stopPreview();try {const response = await api.getAudioResourceFile(row.id);previewUrl = URL.createObjectURL(response.data);previewAudio = new Audio(previewUrl);playingId.value = row.id;previewAudio.onended = stopPreview;previewAudio.onerror = () => {stopPreview();ElMessage.error(t('config.audio_resources.preview_failed'))};await previewAudio.play()} catch (error:any) {stopPreview();ElMessage.error(responseMessage(error))}};
const renameResource = async (row:any) => {try {const {value} = await ElMessageBox.prompt(t('config.audio_resources.rename_prompt'),t('config.audio_resources.rename'),{inputValue:row.name,inputPattern:/\S+/,inputErrorMessage:t('config.audio_resources.name_required'),confirmButtonText:t('button.confirm'),cancelButtonText:t('button.cancel')});const {data} = await api.renameAudioResource(row.id,String(value || '').trim());if (!data?.status) throw new Error(data?.msg);ElMessage.success(t('config.audio_resources.rename_success'));await loadResources()} catch (error:any) {if (error === 'cancel' || error === 'close') return;ElMessage.error(responseMessage(error))}};
const removeResource = async (row:any) => {try {await ElMessageBox.confirm(t('config.audio_resources.delete_confirm',{name:row.name}),t('message.warning'),{type:'warning',confirmButtonText:t('button.delete'),cancelButtonText:t('button.cancel')});const {data} = await api.deleteAudioResource(row.id);if (!data?.status) throw new Error(data?.msg);if (playingId.value === row.id) stopPreview();ElMessage.success(t('config.audio_resources.delete_success'));await loadResources()} catch (error:any) {if (error === 'cancel' || error === 'close') return;ElMessage.error(responseMessage(error))}};
const formatSize = (value:any) => {const bytes = Number(value || 0);return bytes < 1024 ? `${bytes} B` : bytes < 1024 ** 2 ? `${(bytes / 1024).toFixed(1)} KB` : `${(bytes / 1024 ** 2).toFixed(1)} MB`};const referenceText = (references:any[]) => references.map(item => item.scope === 'sop_completed' ? `${item.sopName} · ${t('config.sop_step_config.sop_completion_feedback')}` : `${item.sopName} · ${item.stepName || item.stepId} · ${item.scope === 'operation_error' ? t('config.sop_step_config.operation_error_feedback') : t('config.sop_step_config.operation_complete_feedback')}`).join('\n');onBeforeUnmount(stopPreview);
</script>

<style scoped lang="scss">
.upload-panel{display:grid;grid-template-columns:1fr 1.35fr auto;align-items:center;gap:12px;margin:14px 0 18px;padding:14px;border:1px solid var(--el-border-color-light);background:var(--el-fill-color-lighter)}.upload-panel :deep(.el-upload),.upload-panel :deep(.el-upload-dragger){width:100%}.upload-panel :deep(.el-upload-dragger){display:flex;align-items:center;justify-content:center;gap:8px;height:68px;padding:8px}.upload-panel :deep(.el-upload__tip){margin:0}.upload-icon{font-size:24px;color:var(--bs-primary-color)}.resource-toolbar{display:flex;align-items:center;justify-content:space-between;margin-bottom:10px}.original-name{display:block;margin-top:4px;color:var(--el-text-color-secondary);font-weight:400;word-break:break-all}@media(max-width:760px){.upload-panel{grid-template-columns:1fr}.upload-panel .el-button{width:100%}}
</style>
